sudo: required
dist: trusty
language: node_js
node_js:
- "4.4"
- "4.3"
addons:
apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
- sudo apt-get install update
- sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
- sudo sh -e /etc/init.d/xvfb start
before_scrip:
- npm install
- npm run build
script: npm test
